/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.USStates
	(
	USStates_ID int NOT NULL IDENTITY (1, 1),
	State_Abbrev char(2) NOT NULL,
	State_Description varchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.USStates ADD CONSTRAINT
	PK_USStates_ID PRIMARY KEY CLUSTERED 
	(
	USStates_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.USStates ADD CONSTRAINT
	UK_USStates_State_Abbrev UNIQUE NONCLUSTERED 
	(
	USStates_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.USStates SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
